= Fedora Kinoite User Guide

Welcome to the Fedora Kinoite user guide!

// image::kinoite-logo.svg[Kinoite logo]

_Fedora Kinoite_ is an immutable desktop operating system. It aims to be
extremely stable and reliable. It also aims to be an excellent platform for
developers and for those using container-focused workflows.

[[introduction]]
== Introduction to Kinoite

Kinoite is a variant of the Fedora KDE Spin. It looks, feels and behaves like a
regular desktop operating system, and the experience is similar to what you
find with using a standard Fedora KDE Spin.

However, unlike other operating systems, Kinoite is immutable. This means that
every installation is identical to every other installation of the same
version. The operating system that is on disk is exactly the same from one
machine to the next, and it never changes as it is used.

Kinoite's immutable design is intended to make it more stable, less prone to
bugs, and easier to test and develop. Finally, Kinoite's immutable design also
makes it an excellent platform for containerized applications as well as
container-based software development. In each case, applications (apps) and
containers are kept separate from the host system, improving stability and
reliability.

Kinoite's core technologies have some other helpful features. OS updates are
fast and there's no waiting around for them to install: just reboot as normal
to start using the next version. With Kinoite, it is also possible to roll back
to the previous version of the operating system, if something goes wrong.

[[this-guide]]
== About this guide

In most cases, Kinoite behaves like a standard Fedora KDE installation, and the
https://docs.fedoraproject.org/[standard Fedora documentation] can be used.
This guide covers those areas where Kinoite differs from a standard Fedora KDE,
including:

* link:installation[OS installation]
* link:getting-started[Installing apps and software]
* link:updates-upgrades-rollbacks[OS upgrades and rollbacks]

The primary audience for these docs are new users, who aren't expected to have
specialist knowledge or technical knowledge about Kinoite's internals. However,
some background link:technical-information[technical information] is provided,
for those who are interested and want to learn more.

[[known-bugs]]
== Known bugs

Fedora Kinoite is considered stable since its first release as part of Fedora
35. However it is not complete and there are still some features missing to
make using it a great user experience.

A list of currently known bugs, issues and missing features is compiled in the
https://pagure.io/fedora-kde/SIG/issue/112[KDE SIG tracker]. Feel free to open
a new one if you find something missing or broken.

