site:
  title: Local Preview
  start_page: fedora-kinoite::index.adoc
content:
  sources:
   - url: .
     branches: HEAD
ui:
  bundle:
    url: https://asamalik.fedorapeople.org/ui-bundle.zip
    snapshot: true
  default_layout: with_menu
output:
  clean: true
  dir: ./public
  destinations:
  - provider: archive
runtime:
  fetch: true
  cache_dir: ./cache
asciidoc:
  attributes:
    variant: kinoite
    variant-name: Kinoite
    website: https://kinoite.fedoraproject.org/
    issue-tracker: https://pagure.io/fedora-kde/SIG/issues
    docs-url: https://docs.fedoraproject.org/en-US/fedora-kinoite/
    docs-src: https://pagure.io/fedora-kde/kinoite-docs
    docs-issue: https://pagure.io/fedora-kde/kinoite-docs/issues
    discussion-forum: https://discussion.fedoraproject.org/c/desktop/kinoite
